apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "react-ui"
  namespace: ms
  labels:
    app: "react-ui"
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: "react-ui"
  replicas: 2
  template:
    metadata:
      labels:
        app:  "react-ui"
    spec:
      containers:
      - image: shubhampatil5128/ui
        name:  "react-ui"
        ports:
          - containerPort: 8081
            name: "react-ui"
        resources:
             limits:
                cpu: 500m
             requests:
                cpu: 200m

---

apiVersion: v1
kind: Service
metadata:
  name: "react-ui"
  namespace: ms
spec:
  selector:
    app: "react-ui"
  type: NodePort
  ports:
  - name: "react-ui"
    port: 8080
    targetPort: 8080
---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: react
    namespace: ms
spec:
   scaleTargetRef:
       apiVersion: apps/v1
       kind: Deployment
       name: "react-ui"
   minReplicas: 2
   maxReplicas: 5
   targetCPUUtilizationPercentage: 70
--------
